import '../models/scenario.dart';

class AppStrings {
  static const Map<String, String> en = {
    'appName': 'SafeSteps',
    'tagline': 'Learn. Decide. Stay Safe.',
    'english': 'English',
    'twi': 'Twi (Akan)',
    'greeting': 'Hello! Ready to learn?',
    'helpTitle': 'You are not alone. It' 's okay to ask for help.',
    'helpConfirm': 'Do you want to reach out for help right now?',
    'yes': 'YES',
    'no': 'NO',
    'trustedAdult': 'Talk to a trusted adult',
    'playNext': 'Play Next',
    'continue': 'Continue',
    'whatShouldIDo': 'What should I have done?',
    'pointsEarned': 'Points earned',
    'riskLevel': 'Risk level',
    'keepLearning': 'Keep learning! You are growing stronger.',
    'helpButton': 'Help',
    'progress': 'Progress',
    'settings': 'Settings',
    'exportData': 'Export Session Data',
    'teacherMode': 'Teacher Mode PIN',
    'languageSaved': 'Language saved successfully.',
    'sessionReport': 'SafeSteps Session Report',
    'sessions': 'Sessions',
    'highRiskFlags': 'High risk flags',
    'helpActivations': 'Help button activations',
    'mostCommonRiskyScenario': 'Most common risky scenario',
    'exportDate': 'Export date',
    'safeChoice': 'Safe choice! Good work.',
    'riskyChoice': 'That choice is risky. Think about the consequences.',
    'loginTitle': 'Login',
    'loginSubtitle': 'Choose your role and sign in',
    'loginRoleLabel': 'Select role',
    'studentLogin': 'Student',
    'parentLogin': 'Parent',
    'teacherLogin': 'Teacher',
    'studentName': 'Student Name',
    'parentName': 'Parent Name',
    'teacherName': 'Teacher Name',
    'studentId': 'Student ID',
    'teacherPin': 'Teacher PIN',
    'loginButton': 'Continue',
    'logout': 'Logout',
    'parentDashboard': 'Parent Dashboard',
    'teacherDashboard': 'Teacher Dashboard',
    'noStudentSelected': 'No student selected. Please log in again.',
    'noStudentFiles': 'No student records available yet.',
    'dataLoadError': 'Unable to load data at this time.',
    'sessionDate': 'Session Date',
    'score': 'Score',
    'studentIdLabel': 'Student ID',
    'studentProfile': 'Student Profile',
    'recentRecords': 'Recent Records',
    'searchStudents': 'Search students',
    'riskFilter': 'Risk filter',
    'sortBy': 'Sort by',
    'latest': 'Latest',
    'oldest': 'Oldest',
    'name': 'Name',
    'all': 'All',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'viewProfile': 'View profile',
    'choiceLabel': 'Choice',
    'riskValue': 'Risk',
    'recordDetail': 'Record Detail',
    'noRecordAvailable': 'No record available.',
    'selectStudent': 'Select Student',
    'selectAStudent': 'Select a student to view records',
    'analytics': 'Analytics',
    'exportReport': 'Export Report',
    'averageRisk': 'Average Risk',
    'totalSessions': 'Total Sessions',
    'highRiskSessions': 'High Risk Sessions',
    'trends': 'Trends',
    'highRiskAlert': 'High Risk Alert',
    'studentHasHighRisk': 'Student has completed high-risk sessions',
    'exportedSuccessfully': 'Report exported successfully',
  };

  static const Map<String, String> tw = {
    'appName': 'SafeSteps',
    'tagline': 'Sua. Paw. Teɛ yie.',
    'english': 'Borɔfo',
    'twi': 'Twi (Akan)',
    'greeting': 'Agoo! Wopɛ sɛ wosuaa adeɛ?',
    'helpTitle': 'Woankasa na woho nyɛ wo yaw. Eye sɛ wobisa mmoa.',
    'helpConfirm': 'Wopɛ sɛ wopɛ mmoa afiri seesei?',
    'yes': 'AANE',
    'no': 'DAABI',
    'trustedAdult': 'Kasa kyerɛ onipa a wobetumi agyina no so',
    'playNext': 'Bɔ Daabi',
    'continue': 'Kɔ so',
    'whatShouldIDo': 'Dɛn na meɛyɛeɛ na ɛsɛe?',
    'pointsEarned': 'Nsesa a wunyaa',
    'riskLevel': 'Ɔhaw sɔ',
    'keepLearning': 'Kɔ so sua! Wopɛ yɛ den.',
    'helpButton': 'Mmoa',
    'progress': 'Nkosuo',
    'settings': 'Nhyɛsoɔ',
    'exportData': 'Fa Sessɔn Data',
    'teacherMode': 'Kyerɛkyerɛni PIN',
    'languageSaved': 'Kasa no asie.',
    'sessionReport': 'SafeSteps Sessɔn Amansan',
    'sessions': 'Sessɔn',
    'highRiskFlags': 'Ɛhaw Kɛse Nsɔ',
    'helpActivations': 'Mmoa Bɔ Ato Mu',
    'mostCommonRiskyScenario': 'Ɔhaw kɛse a ɛda no adi',
    'exportDate': 'Fa da',
    'safeChoice': 'Kɔɔ so! Woyɛ adwuma pa.',
    'riskyChoice': 'Apaw yi yɛ ɔhaw. Susuw nea ɛbɛba.',
    'loginTitle': 'Login',
    'loginSubtitle': 'Choose your role and sign in',
    'loginRoleLabel': 'Select role',
    'studentLogin': 'Student',
    'parentLogin': 'Parent',
    'teacherLogin': 'Teacher',
    'studentName': 'Student Name',
    'parentName': 'Parent Name',
    'teacherName': 'Teacher Name',
    'studentId': 'Student ID',
    'teacherPin': 'Teacher PIN',
    'loginButton': 'Continue',
    'logout': 'Logout',
    'parentDashboard': 'Parent Dashboard',
    'teacherDashboard': 'Teacher Dashboard',
    'noStudentSelected': 'No student selected. Please log in again.',
    'noStudentFiles': 'No student records available yet.',
    'dataLoadError': 'Unable to load data at this time.',
    'sessionDate': 'Session Date',
    'score': 'Score',
    'studentIdLabel': 'Student ID',
    'studentProfile': 'Student Profile',
    'recentRecords': 'Recent Records',
    'searchStudents': 'Search students',
    'riskFilter': 'Risk filter',
    'sortBy': 'Sort by',
    'latest': 'Latest',
    'oldest': 'Oldest',
    'name': 'Name',
    'all': 'All',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'viewProfile': 'Hwɛ wo su',
    'choiceLabel': 'Apaw',
    'riskValue': 'Ɔhaw',
    'recordDetail': 'Ɔkwan Akwankyerɛ',
    'noRecordAvailable': 'Osuahunu nka hɔ.',
    'selectStudent': 'Paw Sukuufo',
    'selectAStudent': 'Paw sukuufo bi na hwɛ ne ɔkwan akwankyerɛ',
    'analytics': 'Nkɔmhyɛ',
    'exportReport': 'Fa Amansan',
    'averageRisk': 'Ɔhaw Waacini',
    'totalSessions': 'Sessɔn Nyinaa',
    'highRiskSessions': 'Ɔhaw Kɛse Sessɔn',
    'trends': 'Nkɔm',
    'highRiskAlert': 'Ɔhaw Kɛse Abɔmu',
    'studentHasHighRisk': 'Sukuufo no ayɛ sessɔn a ɔhaw kɛse',
    'exportedSuccessfully': 'Amansan no afa yie',
  };
}

const String hotlineNumber = '+233800800800';

final List<Scenario> allScenarios = [
  Scenario(
    id: 'scenario1',
    title: 'The Job Offer',
    titleTwi: 'Adwuma Akwankyerɛ',
    description:
        'A stranger offers a well-paying job in another city. Choose carefully.',
    descriptionTwi:
        '[Twi: Onipa a wonnim de adwuma a ɛyɛ papa brɛ wo ba kuro foforɔ mu. Paw yie.]',
    audioFileEn: 'scenario1_en.mp3',
    audioFileTw: 'scenario1_tw.mp3',
    weight: 3,
    coverImage: 'assets/images/job_offer.png',
    nodes: [
      ScenarioNode(
        id: 'scenario1_node1',
        text:
            'A stranger calls you with a great job offer. Do you accept without checking?',
        textTwi:
            'Onipa a wonnim frɛ wo na ɔde adwuma pa ba wo so. Wobɛgye no ananmu?',
        choices: [
          Choice(
            id: 'scenario1_choice1',
            text: 'Ask for more details and verify the offer.',
            textTwi: 'Bisa nsɛm pii na hwehwɛ mu yiye.',
            riskValue: 1,
            nextNodeId: '',
            feedbackText: 'Good choice to verify before deciding.',
            feedbackTextTwi:
                'Paw pa. Eye sɛ wuhu no mu yiye ansa na wode wo ho to hɔ.',
          ),
          Choice(
            id: 'scenario1_choice2',
            text: 'Accept immediately without checking.',
            textTwi: 'Gye no ntɛm ara na mma ho kwan.',
            riskValue: 5,
            nextNodeId: '',
            feedbackText:
                'That could be risky. Always verify offers from strangers.',
            feedbackTextTwi: 'Ɛyɛ ɔhaw. Sɔhwɛ ho ansa na woyere wo ho.',
          ),
        ],
        isEnding: true,
        nextNodeId: '',
      ),
    ],
  ),
  Scenario(
    id: 'scenario2',
    title: 'The New Friend',
    titleTwi: 'Adamfoɔ Foforɔ',
    description:
        'An older person befriends you online and wants to meet secretly.',
    descriptionTwi:
        '[Twi: Onipa panyin bi de wo ho bɔ wo ho ban wɔ intanɛt so.]',
    audioFileEn: 'scenario2_en.mp3',
    audioFileTw: 'scenario2_tw.mp3',
    weight: 2,
    coverImage: 'assets/images/new_friend.png',
    nodes: [
      ScenarioNode(
        id: 'scenario2_node1',
        text: 'A new online friend asks to meet in secret. Do you agree?',
        textTwi:
            'Adamfo foforɔ wɔ intanɛt so pɛ sɛ mokɔhyia a obi nni hɔ. Wobɛgye?',
        choices: [
          Choice(
            id: 'scenario2_choice1',
            text: 'Say no and tell a trusted adult.',
            textTwi: 'Ka daabi na ka kyerɛ obi a woagyina no so.',
            riskValue: 1,
            nextNodeId: '',
            feedbackText: 'That is safe and responsible.',
            feedbackTextTwi: 'Ɛyɛ papa na ɛyɛ ɔdɔ mu biribi.',
          ),
          Choice(
            id: 'scenario2_choice2',
            text: 'Go meet them alone.',
            textTwi: 'Kɔhyia no na wo ara nko.',
            riskValue: 5,
            nextNodeId: '',
            feedbackText:
                'This is risky; meeting strangers alone can be harmful.',
            feedbackTextTwi:
                'Ɛyɛ ɔhaw; sɛ wokɔ akɔhyia onipa a wonnim ankyɛ a, ɛbɛtumi asɛe wo.',
          ),
        ],
        isEnding: true,
        nextNodeId: '',
      ),
    ],
  ),
  Scenario(
    id: 'scenario3',
    title: 'Stay or Leave School',
    titleTwi: 'Wobɛtena Anɔpa anaa Wobɛkɔ Adwuma',
    description: 'Family pressure grows to leave school for work.',
    descriptionTwi: '[Twi: Abusua hyɛ wo so sɛ wosane sukuu mu.]',
    audioFileEn: 'scenario3_en.mp3',
    audioFileTw: 'scenario3_tw.mp3',
    weight: 1,
    coverImage: 'assets/images/school_choice.png',
    nodes: [
      ScenarioNode(
        id: 'scenario3_node1',
        text:
            'Your family wants you to quit school for work. What do you choose?',
        textTwi: 'Wo abusua pɛ sɛ wotwa sukuu mu kɔyɛ adwuma. Dɛn na wopaw?',
        choices: [
          Choice(
            id: 'scenario3_choice1',
            text: 'Keep going to school and discuss options with family.',
            textTwi: 'Tena sukuu so na kasa fa akwankyerɛ ho.',
            riskValue: 1,
            nextNodeId: '',
            feedbackText: 'That is a healthy choice for your future.',
            feedbackTextTwi: 'Eye decision ma wo daakye.',
          ),
          Choice(
            id: 'scenario3_choice2',
            text: 'Drop out right away.',
            textTwi: 'Twa sukuu mu ntɛm.',
            riskValue: 5,
            nextNodeId: '',
            feedbackText:
                'Leaving school too soon can limit your opportunities.',
            feedbackTextTwi:
                'Sukuumu mu gyehyɛ mu kɔtɔɔso betumi agya wo kwan.',
          ),
        ],
        isEnding: true,
        nextNodeId: '',
      ),
    ],
  ),
];
